version: '3.8'

services:
  disclosuregame-app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true